apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.database.configmap.name }}
  namespace: {{ .Release.Namespace }}
data:
  db_url: {{ .Release.Name }}-{{ .Values.database.configmap.db_url }}
