apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.name }}
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.volume.capacity }}
  accessModes:
  - {{ .Values.volume.accessMode }}
  storageClassName: {{ .Values.volume.storageClass.name }}
  hostPath:
    path: {{ .Values.volume.hostPath }}
