apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.database.secret.name }}
type: {{ .Values.global.database.secret.type }}
data:
  user: {{ .Values.global.database.secret.user }}
  password: {{ .Values.global.database.secret.password }}
